FROM golang:1.22-alpine AS builder

WORKDIR /app
COPY go.mod  ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /quelpoke ./main.go

FROM alpine:latest
RUN apk --no-cache add ca-certificates
WORKDIR /root/
COPY --from=builder /quelpoke .
EXPOSE 8080
CMD ["./quelpoke"]